apiVersion: v1
kind: Secret
metadata:
  name: prometheus-config-secrets
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  namespace: coffeeshop-monitoring
type: Opaque
data:
  prometheus-additional-config.yaml: <BASE64_FILE_CONTENTS>
