apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-serviceaccount
  namespace: coffeeshop-monitoring
  labels:
    app: strimzi
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: coffeeshop-monitoring
  labels:
    app: strimzi
spec:
  replicas: 1
  serviceAccountName: prometheus-serviceaccount
  serviceMonitorSelector:
    matchLabels:
      app: strimzi
  additionalScrapeConfigs:
    name: prometheus-config-secrets
    key: prometheus-additional-config.yaml
